#pragma config(Motor,  port2,            ,             tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,            ,             tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int rightWheel = 0;
int leftWheel = 0;

void manualOneStickDrive()
{
	//get velocity (forward and backward)
	rightWheel = vexRT[Ch2];
	leftWheel = vexRT[Ch2];
	//adjust velocity to turn (left and right)
	rightWheel -= vexRT[Ch1];
	leftWheel += vexRT[Ch1];
	//set motor velocities
	motor[port2] = leftWheel;
	motor[port3] = rightWheel;
}

void manualTwoStickDrive()
{
	motor[port2] = vexRT[Ch3];
	motor[port3] = vexRT[Ch2];
}

void manualAccelerometerDrive ()
{
	//get velocity (forward and backward)
	rightWheel = vexRT[AccelY];
	leftWheel = vexRT[AccelY];
	//adjust velocity to turn (left and right)
	rightWheel -= vexRT[AccelX];
	leftWheel += vexRT[AccelX];
	//set motor velocities
	motor[port2] = leftWheel;
	motor[port3] = rightWheel;
}

task main()
{
	while(true)
	{
		if(vexRT[Btn6D] == 1)
		{
			manualTwoStickDrive();
		}
		else if (vexRT[Btn6U] == 1)
		{
			manualAccelerometerDrive();
		}
		else
		{
			manualOneStickDrive();
		}

		if((vexRT[Btn5U] == 1 && vexRT[Btn5D] == 1) || (vexRT[Btn5U] == 0 && vexRT[Btn5D] == 0))
		{
			motor[port4] = 0;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[port4] = 127;
		}
		else if(vexRT[Btn5U] == 1)
		{
			motor[port4] = -127;
		}
	}
}
